spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: backweb
          uri: lb://backweb
          predicates:
            - Path=/api/v0/**
server:
  port: 9000
eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: "http://localhost:8761/eureka"